org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false

# Required by unityLibrary/build.gradle - list of streaming asset extensions to not compress
unityStreamingAssets=

# Unity build properties (used by unityLibrary/build.gradle for il2cpp)
unity.androidSdkPath=C:/Users/Asus/AppData/Local/Android/Sdk
unity.androidNdkPath=D:/unityhub/6000.4.2f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
