org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false

# Required by unityLibrary/build.gradle - list of streaming asset extensions to not compress
unityStreamingAssets=

# Unity build properties (used by unityLibrary/build.gradle for il2cpp)
