name: poandroid CI

on:
  push:
    branches: [main, develop, "feature/**", "hotfix/**"]
  pull_request:
    branches: [main, develop]

env:
  JAVA_VERSION: "17"

jobs:
  lint:
    name: Android lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

